import type { Metadata } from "next"
import { Poppins } from "next/font/google"
import "./globals.css"
import NextThemes from "@/components/shared/NextThemes"
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
})

export const metadata: Metadata = {
  title: "MovieHub",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppins.className} mx-auto min-h-screen max-w-[1920px] px-1`}
        suppressHydrationWarning
      >
        <NextThemes
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </NextThemes>
      </body>
    </html>
  )
}
